package com.mooo.mytools.example;

/*
* GetTable.java
*
* Automatically Generated by Expresso's DBTool 
* Copyright goes here.
*/

import java.net.URLEncoder;
import java.util.*;
import java.sql.*;
import org.apache.log4j.Category;


public class GetTableData {

           private static Category log = null;
           
           static public int getID(String Table,String Fild,String Name) throws SQLException,Exception {
              Class.forName("org.gjt.mm.mysql.Driver").newInstance();
            //Class.forName("com.mysql.jdbc.Driver").newInstance();
              Connection connxpcShared = DriverManager.getConnection("jdbc:mysql://localhost/xpcwShared","xpcwuser","click89");
              Connection connBranch = DriverManager.getConnection("jdbc:mysql://localhost/xpcwBranch","xpcwuser","click89");

                Statement stmt = connBranch.createStatement();
                ResultSet rset = null;
                String sql = "SELECT COUNT(ID)";
                sql += " FROM "+Table;
                sql += " WHERE "+Fild+"='"+Name+"'";
               if (log.isDebugEnabled()) log.debug("sql="+sql);
                rset = stmt.executeQuery(sql);
                rset.next();
               if (log.isDebugEnabled()) log.debug("COUNT(ID)="+rset.getInt("COUNT(ID)"));
                if(rset.getInt("COUNT(ID)")!=1) throw new Exception("check LocalPartner databases");
                sql = "SELECT COUNT(ID)";
                sql += " FROM "+Table;
                sql += " WHERE "+Fild+"='"+Name+"'";
                rset = stmt.executeQuery(sql);
                rset.next();
                int intId=rset.getInt("ID");
                return intId;
         }

}
